name: Build Docker Image

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: actorforth/smartbch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set-tag
        run: echo "TAG=$(git -C smartbch describe --always --tags --dirty --abbrev=7 | sed 's/^.*\(.\{7\}\)/\1/')" >> $GITHUB_ENV

      - name: Build docker image
        run: |
          docker build -f smartbch/Dockerfile.mainnet.optimized -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG ./

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push docker images
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG
